source 'https://cdn.cocoapods.org/'
platform :ios, :deployment_target => '13.0'

target 'YandexMobileAdsExample' do
  pod 'YandexMobileAdsAdMobAdapters', '~> 8.0.0.0-beta.2'
  pod 'YandexMobileAdsMediation', '~> 8.0.0-beta.2'
  pod 'YandexMobileAdsInstream'
  pod 'YandexMobileAdsConsentManagement'
end
